
export const ALL_TIMELINE = [1, 2, 3];
export const DEFAULT_TIMELINE = ALL_TIMELINE[0];

// Timeline actions
export const UPDATE_CURRENT_TIMELINE_REQUEST = 'timeline/UPDATE_CURRENT_TIMELINE_REQUEST';
export const UPDATE_CURRENT_TIMELINE = 'timeline/UPDATE_CURRENT_TIMELINE';
